// Bengali translations for all 114 Surahs
export interface BengaliSurahInfo {
  nameBangla: string;
  meaningBangla: string;
}

export const BENGALI_SURAHS: Record<number, BengaliSurahInfo> = {
  1: { nameBangla: "আল ফাতিহা", meaningBangla: "সূচনা" },
  2: { nameBangla: "আল বাকারাহ", meaningBangla: "বকনা-বাছুর" },
  3: { nameBangla: "আলে ইমরান", meaningBangla: "ইমরানের পরিবার" },
  4: { nameBangla: "আন নিসা", meaningBangla: "নারী" },
  5: { nameBangla: "আল মায়িদাহ", meaningBangla: "খাদ্য পরিবেশিত টেবিল" },
  6: { nameBangla: "আল আনআম", meaningBangla: "গৃহপালিত পশু" },
  7: { nameBangla: "আল আরাফ", meaningBangla: "উঁচু স্থানসমূহ" },
  8: { nameBangla: "আল আনফাল", meaningBangla: "যুদ্ধলব্ধ ধন-সম্পদ" },
  9: { nameBangla: "আত তাওবাহ", meaningBangla: "অনুতাপ" },
  10: { nameBangla: "ইউনুস", meaningBangla: "নবী ইউনুস" },
  11: { nameBangla: "হুদ", meaningBangla: "নবী হুদ" },
  12: { nameBangla: "ইউসুফ", meaningBangla: "নবী ইউসুফ" },
  13: { nameBangla: "আর রা'দ", meaningBangla: "বজ্রপাত" },
  14: { nameBangla: "ইব্রাহিম", meaningBangla: "নবী ইব্রাহিম" },
  15: { nameBangla: "আল হিজর", meaningBangla: "পাথুরে পাহাড়" },
  16: { nameBangla: "আন নাহল", meaningBangla: "মৌমাছি" },
  17: { nameBangla: "আল ইসরা", meaningBangla: "নৈশ ভ্রমণ" },
  18: { nameBangla: "আল কাহফ", meaningBangla: "গুহা" },
  19: { nameBangla: "মারইয়াম", meaningBangla: "মারইয়াম (ঈসা আঃ এর মাতা)" },
  20: { nameBangla: "ত্বোয়া-হা", meaningBangla: "ত্বোয়া-হা" },
  21: { nameBangla: "আল আম্বিয়া", meaningBangla: "নবীগণ" },
  22: { nameBangla: "আল হাজ্জ", meaningBangla: "হজ্জ" },
  23: { nameBangla: "আল মু'মিনুন", meaningBangla: "বিশ্বাসীগণ" },
  24: { nameBangla: "আন নূর", meaningBangla: "জ্যোতি" },
  25: { nameBangla: "আল ফুরকান", meaningBangla: "সত্য-মিথ্যার পার্থক্যকারী" },
  26: { nameBangla: "আশ শুআরা", meaningBangla: "কবিগণ" },
  27: { nameBangla: "আন নামল", meaningBangla: "পিপীলিকা" },
  28: { nameBangla: "আল কাসাস", meaningBangla: "কাহিনীর বিবরণ" },
  29: { nameBangla: "আল আনকাবুত", meaningBangla: "মাকড়সা" },
  30: { nameBangla: "আর রুম", meaningBangla: "রোমান সাম্রাজ্য" },
  31: { nameBangla: "লুকমান", meaningBangla: "জ্ঞানী লুকমান" },
  32: { nameBangla: "আস সাজদাহ", meaningBangla: "সিজদা" },
  33: { nameBangla: "আল আহজাব", meaningBangla: "জোট" },
  34: { nameBangla: "সাবা", meaningBangla: "সাবা রানী" },
  35: { nameBangla: "ফাতির", meaningBangla: "আদি স্রষ্টা" },
  36: { nameBangla: "ইয়াসীন", meaningBangla: "ইয়াসীন" },
  37: { nameBangla: "আস সাফফাত", meaningBangla: "সারিবদ্ধভাবে দাঁড়ানো" },
  38: { nameBangla: "সোয়াদ", meaningBangla: "সোয়াদ" },
  39: { nameBangla: "আজ জুমার", meaningBangla: "দলসমূহ" },
  40: { nameBangla: "গাফির", meaningBangla: "ক্ষমাকারী" },
  41: { nameBangla: "ফুসসিলাত", meaningBangla: "সুস্পষ্ট বিবরণ" },
  42: { nameBangla: "আশ শূরা", meaningBangla: "পরামর্শ" },
  43: { nameBangla: "আজ জুখরুফ", meaningBangla: "স্বর্ণালঙ্কার" },
  44: { nameBangla: "আদ দুখান", meaningBangla: "ধোঁয়া" },
  45: { nameBangla: "আল জাসিয়াহ", meaningBangla: "নতজানু" },
  46: { nameBangla: "আল আহকাফ", meaningBangla: "বালিয়াড়ি" },
  47: { nameBangla: "মুহাম্মদ", meaningBangla: "নবী মুহাম্মদ (সাঃ)" },
  48: { nameBangla: "আল ফাতহ", meaningBangla: "বিজয়" },
  49: { nameBangla: "আল হুজুরাত", meaningBangla: "বাসগৃহসমূহ" },
  50: { nameBangla: "কাফ", meaningBangla: "কাফ" },
  51: { nameBangla: "আদ জারিয়াত", meaningBangla: "বিক্ষেপকারী বাতাস" },
  52: { nameBangla: "আত তূর", meaningBangla: "তূর পর্বত" },
  53: { nameBangla: "আন নাজম", meaningBangla: "তারা" },
  54: { nameBangla: "আল কামার", meaningBangla: "চন্দ্র" },
  55: { nameBangla: "আর রহমান", meaningBangla: "পরম করুণাময়" },
  56: { nameBangla: "আল ওয়াকিয়াহ", meaningBangla: "নিশ্চিত ঘটনা" },
  57: { nameBangla: "আল হাদিদ", meaningBangla: "লোহা" },
  58: { nameBangla: "আল মুজাদিলাহ", meaningBangla: "অনুযোগকারিণী নারী" },
  59: { nameBangla: "আল হাশর", meaningBangla: "পুনরুত্থান ও সমাবেশ" },
  60: { nameBangla: "আল মুমতাহানাহ", meaningBangla: "পরীক্ষার্থিনী নারী" },
  61: { nameBangla: "আস সাফ", meaningBangla: "সারিবদ্ধ সৈন্যদল" },
  62: { nameBangla: "আল জুমুআহ", meaningBangla: "শুক্রবার" },
  63: { nameBangla: "আল মুনাফিকুন", meaningBangla: "কপট বিশ্বাসীগণ" },
  64: { nameBangla: "আত তাগাবুন", meaningBangla: "ক্ষতি ও লাভ" },
  65: { nameBangla: "আত তালাক", meaningBangla: "তালাক বা বিবাহবিচ্ছেদ" },
  66: { nameBangla: "আত তাহরিম", meaningBangla: "নিষিদ্ধকরণ" },
  67: { nameBangla: "আল মুলক", meaningBangla: "সার্বভৌমত্ব" },
  68: { nameBangla: "আল কালাম", meaningBangla: "কলম" },
  69: { nameBangla: "আল হাক্কাহ", meaningBangla: "অনিবার্য সত্য" },
  70: { nameBangla: "আল মাআরিজ", meaningBangla: "উন্মুক্ত সোপান" },
  71: { nameBangla: "নূহ", meaningBangla: "নবী নূহ" },
  72: { nameBangla: "আল জিন", meaningBangla: "জ্বীন সম্প্রদায়" },
  73: { nameBangla: "আল মুজ্জাম্মিল", meaningBangla: "বস্ত্রাবৃত করনেওয়ালা" },
  74: { nameBangla: "আল মুদ্দাসসির", meaningBangla: "চাদরাবৃত করনেওয়ালা" },
  75: { nameBangla: "আল কিয়ামাহ", meaningBangla: "পুনরুত্থান দিবস" },
  76: { nameBangla: "আল ইনসান", meaningBangla: "মানবজাতি" },
  77: { nameBangla: "আল মুরসালাত", meaningBangla: "প্রেরিত বায়ু" },
  78: { nameBangla: "আন নাবা", meaningBangla: "মহাকাহন / মহাসংবাদ" },
  79: { nameBangla: "আন নাযিয়াত", meaningBangla: "আত্মা হরণকারী ফেরেশতা" },
  80: { nameBangla: "আবাসা", meaningBangla: "ভ্রুকুঞ্চিত করা" },
  81: { nameBangla: "আত তাকউইর", meaningBangla: "আচ্ছন্ন করা" },
  82: { nameBangla: "আল ইনফিতার", meaningBangla: "বিদীর্ণ করা" },
  83: { nameBangla: "আল মুতাফফিফিন", meaningBangla: "ওজনে কম প্রদানকারী" },
  84: { nameBangla: "আল ইনশিকাক", meaningBangla: "খণ্ড-বিখণ্ড করা" },
  85: { nameBangla: "আল বুরুজ", meaningBangla: "নক্ষত্রপুঞ্জ" },
  86: { nameBangla: "আত তারিক", meaningBangla: "রাতের আগন্তুক" },
  87: { nameBangla: "আল আ'লা", meaningBangla: "সর্বোচ্চ" },
  88: { nameBangla: "আল গাশিয়াহ", meaningBangla: "অভিভূতকারী দুর্যোগ" },
  89: { nameBangla: "আল ফজর", meaningBangla: "প্রভাতকাল" },
  90: { nameBangla: "আল বালাদ", meaningBangla: "নগর" },
  91: { nameBangla: "আশ শামস", meaningBangla: "সূর্য" },
  92: { nameBangla: "আল লাইল", meaningBangla: "রাত্রি" },
  93: { nameBangla: "আদ দুহা", meaningBangla: "পূর্বাহ্নের রোদ" },
  94: { nameBangla: "আশ শারহ", meaningBangla: "বক্ষ প্রসারণ করা" },
  95: { nameBangla: "আত তীন", meaningBangla: "ডুমুর ফল" },
  96: { nameBangla: "আল আলাক", meaningBangla: "রক্তপিণ্ড" },
  97: { nameBangla: "আল কদর", meaningBangla: "মহিমান্বিত রজনী" },
  98: { nameBangla: "আল বাইয়্যিনাহ", meaningBangla: "সুস্পষ্ট প্রমাণ" },
  99: { nameBangla: "আজ জিলজাল", meaningBangla: "ভূমিকম্প" },
  100: { nameBangla: "আল আদিয়াত", meaningBangla: "অভিযানকারী অশ্বসমূহ" },
  101: { nameBangla: "আল কারিয়াহ", meaningBangla: "মহাসংকট" },
  102: { nameBangla: "আত তাকাসুর", meaningBangla: "প্রাচুর্যের প্রতিযোগিতা" },
  103: { nameBangla: "আল আসর", meaningBangla: "সময়" },
  104: { nameBangla: "আল হুমাজাহ", meaningBangla: "নিন্দাকারী" },
  105: { nameBangla: "আল ফীল", meaningBangla: "হাতি" },
  106: { nameBangla: "কুরাইশ", meaningBangla: "কুরাইশ গোত্র" },
  107: { nameBangla: "আল মাউন", meaningBangla: "নিত্যপ্রয়োজনীয় জিনিসপত্র" },
  108: { nameBangla: "আল কাওসার", meaningBangla: "প্রচুর কল্যাণ / ঝর্ণা" },
  109: { nameBangla: "আল কাফিরুন", meaningBangla: "অবিশ্বাসী দল" },
  110: { nameBangla: "আন নাসর", meaningBangla: "সাহায্য" },
  111: { nameBangla: "আল মাসাদ", meaningBangla: "খেজুরের পাকানো রশি" },
  112: { nameBangla: "আল ইখলাস", meaningBangla: "একনিষ্ঠতা" },
  113: { nameBangla: "আল ফালাক", meaningBangla: "ঊষাকাল" },
  114: { nameBangla: "আন নাস", meaningBangla: "মানবজাতি" }
};
